# -*- coding: utf-8 -*-
# Deployment settings for ghosthunter.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/win/Marmalade/6.2/s3e/makefile_builder/mkb.py', 'z:/ghosthunter/ghosthunter/trunk/ghosthunter.mkb', '--deploy-only']
mkb = 'z:/ghosthunter/ghosthunter/trunk/ghosthunter.mkb'
mkf = []

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('z:/ghosthunter/ghosthunter/trunk\data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'ghosthunter'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'ghosthunter'
    long_caption = 'ghosthunter'
    version = [0, 0, 1]
    config = ['z:/ghosthunter/ghosthunter/trunk/data/app.icf']
    data_dir = 'z:/ghosthunter/ghosthunter/trunk/data'
    iphone_link_lib = []
    linux_ext_lib = []
    iphone_link_libdir = []
    iphone_link_opts = []
    osx_ext_dll = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    android_extra_application_manifest = []
    win32_ext_dll = []
    android_so = []
    iphone_link_libs = []
    target = {
         'arm' : {
                   'debug'   : r'z:/ghosthunter/ghosthunter/trunk/build_ghosthunter_vc10/Debug_ghosthunter_VC10_arm/ghosthunter.s3e',
                   'release' : r'z:/ghosthunter/ghosthunter/trunk/build_ghosthunter_vc10/Release_ghosthunter_VC10_arm/ghosthunter.s3e',
                 },
         'mips_gcc' : {
                   'debug'   : r'z:/ghosthunter/ghosthunter/trunk/build_ghosthunter_vc10/Debug_ghosthunter_VC10_gcc_mips/ghosthunter.so',
                   'release' : r'z:/ghosthunter/ghosthunter/trunk/build_ghosthunter_vc10/Release_ghosthunter_VC10_gcc_mips/ghosthunter.so',
                 },
         'x86' : {
                   'debug'   : r'z:/ghosthunter/ghosthunter/trunk/build_ghosthunter_vc10/Debug_ghosthunter_VC10_x86/ghosthunter.s86',
                   'release' : r'z:/ghosthunter/ghosthunter/trunk/build_ghosthunter_vc10/Release_ghosthunter_VC10_x86/ghosthunter.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'z:/ghosthunter/ghosthunter/trunk/build_ghosthunter_vc10/Debug_ghosthunter_VC10_gcc_arm/ghosthunter.s3e',
                   'release' : r'z:/ghosthunter/ghosthunter/trunk/build_ghosthunter_vc10/Release_ghosthunter_VC10_gcc_arm/ghosthunter.s3e',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
